//! Combined dispatch enums for Construct / Stream / Evaluate traits.
//!
//! This module defines [`CombinedConstruct`], an enum that wraps all 70 built-in
//! construct types and implements [`Construct`] via `enum_dispatch`, replacing
//! `Box<CombinedConstruct>` with `Box<CombinedConstruct>` for zero-overhead static
//! dispatch.
//!
//! `CombinedStream` and `CombinedExpr` are defined alongside their respective
//! traits in [`core::stream`] and [`expr`].

use crate::core::{Renamed, Subconstruct};

// ===========================================================================
// CombinedConstruct enum
// ===========================================================================

/// enum_dispatch wrapper enum that replaces `Box<CombinedConstruct>`.
///
/// All 70 built-in constructors are variants. `Compressed` is gated behind
/// the `compression` feature. Each variant holds the concrete construct type,
/// and [`Construct`] methods are dispatched via a `match` generated by
/// `enum_dispatch`, allowing the compiler to inline calls.
#[allow(clippy::large_enum_variant)]
#[enum_dispatch::enum_dispatch(Construct)]
pub enum CombinedConstruct {
    // core
    /// Wraps [`Subconstruct`].
    Subconstruct(Subconstruct),
    /// Wraps [`Renamed`].
    Renamed(Renamed),
    // atomic
    /// Wraps `FormatField`.
    FormatField(crate::constructs::format_field::FormatField),
    /// Wraps `Bytes`.
    Bytes(crate::constructs::bytes::Bytes),
    /// Wraps `GreedyBytes`.
    GreedyBytes(crate::constructs::bytes::GreedyBytes),
    /// Wraps `BytesExpr`.
    BytesExpr(crate::constructs::bytes::BytesExpr),
    /// Wraps `BytesInteger`.
    BytesInteger(crate::constructs::bytes_integer::BytesInteger),
    /// Wraps `BitsInteger`.
    BitsInteger(crate::constructs::bytes_integer::BitsInteger),
    /// Wraps `VarInt`.
    VarInt(crate::constructs::varint::VarInt),
    /// Wraps `ZigZag`.
    ZigZag(crate::constructs::varint::ZigZag),
    /// Wraps `Flag`.
    Flag(crate::constructs::flag::Flag),
    /// Wraps `CString`.
    CString(crate::constructs::strings::CString),
    /// Wraps `PaddedString`.
    PaddedString(crate::constructs::strings::PaddedString),
    /// Wraps `Const`.
    Const(crate::constructs::const_::Const),
    /// Wraps `Mapping`.
    Mapping(crate::constructs::enum_::Mapping),
    // adapters
    /// Wraps `Adapter`.
    Adapter(crate::constructs::adapters::Adapter),
    /// Wraps `SymmetricAdapter`.
    SymmetricAdapter(crate::constructs::adapters::SymmetricAdapter),
    /// Wraps `ExprAdapter`.
    ExprAdapter(crate::constructs::adapters::ExprAdapter),
    /// Wraps `Validator`.
    Validator(crate::constructs::adapters::Validator),
    /// Wraps `ExprValidator`.
    ExprValidator(crate::constructs::adapters::ExprValidator),
    // meta
    /// Wraps `Pass`.
    Pass(crate::constructs::meta::Pass),
    /// Wraps `Terminated`.
    Terminated(crate::constructs::meta::Terminated),
    /// Wraps `Tell`.
    Tell(crate::constructs::meta::Tell),
    /// Wraps `Seek`.
    Seek(crate::constructs::meta::Seek),
    /// Wraps `SeekExpr`.
    SeekExpr(crate::constructs::meta::SeekExpr),
    /// Wraps `Error`.
    Error(crate::constructs::meta::Error),
    // composite
    /// Wraps `Struct`.
    Struct(crate::constructs::struct_::Struct),
    /// Wraps `Sequence`.
    Sequence(crate::constructs::sequence::Sequence),
    /// Wraps `Union`.
    Union(crate::constructs::union::Union),
    /// Wraps `Select`.
    Select(crate::constructs::select::Select),
    /// Wraps `FocusedSeq`.
    FocusedSeq(crate::constructs::focused_seq::FocusedSeq),
    // enum/computed
    /// Wraps `Enum`.
    Enum(crate::constructs::enum_::Enum),
    /// Wraps `FlagsEnum`.
    FlagsEnum(crate::constructs::enum_::FlagsEnum),
    /// Wraps `Computed`.
    Computed(crate::constructs::computed::Computed),
    /// Wraps `Rebuild`.
    Rebuild(crate::constructs::computed::Rebuild),
    /// Wraps `Default`.
    Default(crate::constructs::computed::Default),
    /// Wraps `Index`.
    Index(crate::constructs::computed::Index),
    /// Wraps `Padded`.
    Padded(crate::constructs::computed::Padded),
    /// Wraps `Aligned`.
    Aligned(crate::constructs::computed::Aligned),
    /// Wraps `FixedSized`.
    FixedSized(crate::constructs::computed::FixedSized),
    /// Wraps `NamedTuple`.
    NamedTuple(crate::constructs::computed::NamedTuple),
    /// Wraps `TimestampAdapter`.
    TimestampAdapter(crate::constructs::computed::TimestampAdapter),
    // repetition
    /// Wraps `Array`.
    Array(crate::constructs::repetition::Array),
    /// Wraps `ArrayExpr`.
    ArrayExpr(crate::constructs::repetition::ArrayExpr),
    /// Wraps `GreedyRange`.
    GreedyRange(crate::constructs::repetition::GreedyRange),
    /// Wraps `RepeatUntil`.
    RepeatUntil(crate::constructs::repetition::RepeatUntil),
    // lazy
    /// Wraps `Lazy`.
    Lazy(crate::constructs::lazy::Lazy),
    /// Wraps `LazyStruct`.
    LazyStruct(crate::constructs::lazy::LazyStruct),
    /// Wraps `LazyArray`.
    LazyArray(crate::constructs::lazy::LazyArray),
    /// Wraps `Rebuffered`.
    Rebuffered(crate::constructs::lazy::Rebuffered),
    // stream ops / tunneling
    /// Wraps `Bitwise`.
    Bitwise(crate::constructs::stream_ops::Bitwise),
    /// Wraps `Bytewise`.
    Bytewise(crate::constructs::stream_ops::Bytewise),
    /// Wraps `Pointer`.
    Pointer(crate::constructs::stream_ops::Pointer),
    /// Wraps `PointerExpr`.
    PointerExpr(crate::constructs::stream_ops::PointerExpr),
    /// Wraps `Peek`.
    Peek(crate::constructs::stream_ops::Peek),
    /// Wraps `RawCopy`.
    RawCopy(crate::constructs::stream_ops::RawCopy),
    /// Wraps `Prefixed`.
    Prefixed(crate::constructs::stream_ops::Prefixed),
    /// Wraps `Transformed`.
    Transformed(crate::constructs::stream_ops::Transformed),
    /// Wraps `Restreamed`.
    Restreamed(crate::constructs::stream_ops::Restreamed),
    /// Wraps `Compressed` (feature-gated).
    #[cfg(feature = "compression")]
    Compressed(crate::constructs::stream_ops::Compressed),
    /// Wraps `Checksum`.
    Checksum(crate::constructs::stream_ops::Checksum),
    /// Wraps `ByteSwapped`.
    ByteSwapped(crate::constructs::stream_ops::ByteSwapped),
    /// Wraps `BitsSwapped`.
    BitsSwapped(crate::constructs::stream_ops::BitsSwapped),
    /// Wraps `LazyBound`.
    LazyBound(crate::constructs::stream_ops::LazyBound),
    // control flow
    /// Wraps `IfThenElse`.
    IfThenElse(crate::constructs::control_flow::IfThenElse),
    /// Wraps `Switch`.
    Switch(crate::constructs::control_flow::Switch),
    /// Wraps `Check`.
    Check(crate::constructs::control_flow::Check),
    /// Wraps `StopIf`.
    StopIf(crate::constructs::control_flow::StopIf),
    // formatting wrappers
    /// Wraps `Hex`.
    Hex(crate::constructs::hex::Hex),
    /// Wraps `HexDump`.
    HexDump(crate::constructs::hex::HexDump),
    /// Catch-all for user-defined or test constructs that are not enum variants.
    ///
    /// Uses dynamic dispatch via `Arc<dyn Construct>` (I3 correction: migrated
    /// from `Box<dyn Construct>` so the variant is cloneable at compile time —
    /// `BuildConstruct::compile` takes `&self` and needs `Arc::clone` to hand
    /// the inner construct to `CompiledDynamic`). Prefer adding a named
    /// variant for performance-critical constructs.
    Dynamic(std::sync::Arc<dyn crate::core::Construct>),
}

/// Unboxes a [`Box<CombinedConstruct>`] into a [`CombinedConstruct`].
///
/// This allows code that already holds a `Box<CombinedConstruct>` to pass it
/// where an `impl Into<CombinedConstruct>` is expected.
impl From<Box<CombinedConstruct>> for CombinedConstruct {
    fn from(b: Box<CombinedConstruct>) -> Self {
        *b
    }
}

/// Wraps any `Construct` into a [`CombinedConstruct::Dynamic`] variant.
///
/// Use this for user-defined or test constructs that are not enum variants.
/// For built-in constructs, prefer `.into()` which uses static dispatch.
///
/// The construct is stored behind an `Arc<dyn Construct>` (I3 correction),
/// enabling compile-time cloning during schema compilation.
#[must_use]
pub fn dynamic<C: crate::core::Construct + 'static>(c: C) -> CombinedConstruct {
    CombinedConstruct::Dynamic(std::sync::Arc::new(c))
}
